GET http://localhost:8080/participants/61b659845d9591ece3dcd0f9

###

PATCH http://localhost:8080/participants/61b659845d9591ece3dcd0f9
Accept: application/json
Content-Type: application/json

{
    "lastname":"NDIAYE",
    "firstname": "Fatoumata",
    "courses" :[
        "61b65a91a16510a70322b499",
        "61b65a91a16510a70322b49a",
        "61b65a91a16510a70322b49c"
    ]

}
