GET http://localhost:8080/participants/61b658e2ec9fbb7002a2f788

###
DELETE http://localhost:8080/participants/61b659845d9591ece3dcd0f9

###
GET http://localhost:8080/participants

###
GET http://localhost:8080/participants/courses

###
PATCH http://localhost:8080/participants/61b658e2ec9fbb7002a2f788
Accept: application/json
Content-Type: application/json

{
    "lastname":"DIOP"
}

###

POST http://localhost:8080/participants
Accept: application/json
Content-Type: application/json

{
    "lastname":"DIOP",
    "firstname": "LAMINE",
    "courses" :[
        "61b65a91a16510a70322b49a",
        "61b65a91a16510a70322b49c"
    ]

}



###

GET http://localhost:8080/courses/

###
DELETE http://localhost:8080/courses/61bb5ce3adc99355db2d24d0

###
GET http://localhost:8080/courses/61b65a91a16510a70322b49d

###
GET http://localhost:8080/courses/courses

###
PATCH http://localhost:8080/courses/61bb5d3eadc99355db2d24d3
Accept: application/json
Content-Type: application/json

{

    "label": "PHYSIQUE",
    "description": "Description du cours de physique",
    "volume": 200
  
}

###

POST http://localhost:8080/courses
Accept: application/json
Content-Type: application/json

{

    "label": "MATH",
    "description": "Description du cours",
    "volume": 111
  
}

